services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual_budget
    restart: unless-stopped
    volumes:
      - $HOME/homelab-data/services-config/actual:/data
    labels:
      - proxy.port=5006
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true