services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC1.1
    container_name: mealie
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - $HOME/homelab-data/services-config/mealie:/app/data/
    environment:
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.rpajo.com
    labels:
      - proxy.port=9000
    networks:
      - proxy

volumes:
  mealie-data:
    driver: local

networks:
  proxy:
    name: proxy
    external: true